global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'medoata44@gmail.com'
  smtp_auth_username: 'medoata44@gmail.com'
  smtp_auth_password: 'gzjmecqbmketlogl'
  smtp_require_tls: false

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: 'all-channels'
    - match:
        severity: warning
      receiver: 'email-only'

receivers:
  - name: 'default'
    email_configs:
      - to: 'medoata44@gmail.com'

  - name: 'all-channels'
    email_configs:
      - to: 'medoata44@gmail.com'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#general'
        text: 'CRITICAL: {{ .GroupLabels.alertname }}'
    webhook_configs:
      - url: 'https://webhook.site/1194a021-ff84-42cf-95a8-bb048188cd3c'
        send_resolved: true

  - name: 'email-only'
    email_configs:
      - to: 'medoata44@gmail.com'
