global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'medoata44@gmail.com'
  smtp_auth_username: 'medoata44@gmail.com'
  smtp_auth_password: 'bjti iior etgk zrtq'
  smtp_require_tls: true

route:
  receiver: 'default'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: 'all-channels'
    - match:
        severity: warning
      receiver: 'email-only'

receivers:
  - name: 'default'
    email_configs:
      - to: 'medoata44@gmail.com'

  - name: 'all-channels'
    email_configs:
      - to: 'medoata44@gmail.com'
    
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#general'
    
    webhook_configs:
      - url: 'https://webhook.site/1194a021-ff84-42cf-95a8-bb048188cd3c'
        send_resolved: true
      - url: 'https://thebesedu.webhook.office.com/webhookb2/42a0b8f7-4afa-4c9a-9e7e-900a49e6ad7d@63b61d0f-184a-4561-b17f-055e99e50890/IncomingWebhook/f2d170fe8df4454eb8e20350ac54fbfd/912240e8-da75-49fe-8308-28c9534977de/V2xQARaPEKGzt1FAgSe8zZU4h9gs5HeJMqjQz7frIsMBk1'
        send_resolved: true

  - name: 'email-only'
    email_configs:
      - to: 'medoata44@gmail.com'