global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # تطبيق .NET 8 محلي على المنفذ الصحيح
  - job_name: 'dotnet8-app'
    static_configs:
      - targets: 
        - 'host.docker.internal:32768'  # المنفذ الفعلي
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http

  # فحص صحة تطبيق .NET 8 عبر Blackbox
  - job_name: 'dotnet8-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:32768/health
        - http://host.docker.internal:32768/api/test/metrics-test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Blackbox exporter for HTTP probes
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        # External partner APIs - replace with your actual endpoints
        - https://api.partner1.com/health
        - https://api.partner2.com/status
        - https://api.partner3.com/ping
        # Internal services
        - http://internal-service-1:8080/health
        - http://internal-service-2:8081/status
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox exporter address

  # Blackbox exporter for HTTPS/SSL certificate monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.partner1.com
        - https://api.partner2.com
        - https://your-domain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # TCP connectivity checks (optional)
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - database-server:5432
        - redis-server:6379
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  # Blackbox exporter metrics
  - job_name: 'blackbox'
    static_configs:
      - targets: ['localhost:9115']